### ISSUE TITLE
0x0 nope

### ISSUE THREAD

**Issue by th3ken-dev** [madiskoivopuu/cs2skinchangermenu#1]

**Comment by th3ken-dev** [comment]
![image](https://github.com/madiskoivopuu/cs2skinchangermenu/assets/39413139/914f6d94-65f5-46ec-91e4-3b0bc40d087f)

**Comment by th3ken-dev** [comment]
menu key ?

**Comment by madiskoivopuu** [comment]
You’ll need to install DirectXTex with vcpkg for that header file. 
PgDown key to open the menu.

**Comment by th3ken-dev** [comment]
I pressed it but there is no menu

**Comment by madiskoivopuu** [comment]
If a command prompt does not show up after injecting the dll, then you'll need to update the patterns for the new CS2 version. The current patterns are for the August build of CS2

**Comment by th3ken-dev** [comment]
Where exactly are these patterns?

**Comment by madiskoivopuu** [comment]
You can find them here https://github.com/madiskoivopuu/cs2skinchangermenu/blob/master/cs2skinchangermenu/memory/patterns.h

**Comment by th3ken-dev** [comment]
Where can I find the latest ones?

**Comment by madiskoivopuu** [comment]
You’ll have to use IDA, Ghidra or something similar to analyze the game DLL files.

**Comment by th3ken-dev** [comment]
Isn't it shared elsewhere?

**Comment by madiskoivopuu** [comment]
Maybe on unknowncheats

**Comment by th3ken-dev** [comment]
I couldn't find the topic patterns
