### ISSUE TITLE
Can you provide the latest feature codes?

### ISSUE THREAD

**Issue by jackKiZhu** [madiskoivopuu/cs2skinchangermenu#2]
After testing, I found that PATTERN_ SPAWNSETSTATTRAK_ PTR is incorrect, can provide the latest PATTERN_ SPAWNSETSTATTRAK_ PTR?

**Comment by madiskoivopuu** [comment]
Yes

**Comment by jackKiZhu** [comment]
> Yes

So the latest PATTERN_ SPAWNSETSTATTRAK_ PTR? Thank you!
